Corrigi o retorno da função ``date_pagination`` quando a data tem o mesmo ano.
scieloorg/articlemetaapi pull request #12
Opened 2020-07-03 19:07 UTC by jamilatta

Essa correção é um tanto quando diferente, ela corrigi uma função que ajusta comportamento do **AM(Article Meta)**. 

Essa API(função) ela cria uma páginação no **deslocamento** evitando que o cursor do Mongo se torne um "gargalo". 

Identificamos em uma atividade de coleta dos dados no **AM** que para o mesmo ano de coleta o retorno era sempre até o final do ano informado.

Para realizar um teste manual: 

```
from articlemeta.client import RestfulClient

art = RestfulClient()

for d in art.documents(from_date='2020-05-15', until_date='2020-05-16'):
    print(d.processing_date)
````

Ticket relacionado: https://github.com/scieloorg/articlemetaapi/issues/11

2020-07-03 22:00 UTC, robertatakenaka approved these changes
Me parece ok

2020-07-06 13:19 UTC, gustavofonseca requested changes
A mudança na função `dates_pagination` resolve o problema, entretanto há outras mudanças de formatação no código que eu penso que podem ser evitadas já que apenas sujam o diff.

2020-07-06 13:19 UTC, gustavofonseca commented on articlemeta/client.py
> +    ARTICLEMETA_URL = 'http://127.0.0.1:8000'
Essa mudança não é desejada.

2020-07-06 18:53 UTC, jamilatta commented on articlemeta/client.py
> +    ARTICLEMETA_URL = 'http://127.0.0.1:8000'
Ao meu ver sim.

2020-07-06 18:58 UTC, gustavofonseca commented on articlemeta/client.py
> +    ARTICLEMETA_URL = 'http://127.0.0.1:8000'
Como assim?

2020-07-08 12:13 UTC, gustavofonseca commented
@jamilatta, poderia enviar o novo commit com as correções para finalizarmos esta atividade?

2020-07-08 12:17 UTC, jamilatta commented
Claro

2020-07-08 12:22 UTC, jamilatta commented
@gustavofonseca solicitei revisão novamente para @robertatakenaka e você.

2020-07-08 16:36 UTC, gustavofonseca approved these changes
Me parece bom =]

2020-07-08 16:37 UTC, merged